using System;
using System.Windows;
using System.Windows.Controls;
using System.Data;
using System.Data.SqlClient;

namespace _46
{
    public partial class Stats : Window
    {
        string connectionStr = null;
        SqlConnection connection = null;
        SqlDataAdapter adapter = null;
        DataTable dt;
        public Stats()
        {
            InitializeComponent();
            connectionStr = "Data Source = DMYTRO; Initial Catalog = Cursova; Integrated Security = True";
            Combo.SelectedIndex = 0;

        }
        private void ExitClick(object sender, RoutedEventArgs e)
        {
            MainWindow mw = new MainWindow();
            Hide();
            mw.Show();
        }
        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            System.Windows.Application.Current.Shutdown();
        }
        int index;
        private void Combo_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            Output.Columns.Clear();
            connection = new SqlConnection(connectionStr);
            connection.Open();

            string strQ;
            if (Combo.SelectedIndex == 0)
            {
                strQ = $"SELECT (dbo.Clients.Surname + ' ' + dbo.Clients.Name + ' ' + dbo.Clients.SecondName) as ПІБ, Count(*) as [Кількість Договорів] " +
                    $"FROM dbo.Contract INNER JOIN dbo.Clients ON dbo.Contract.IDClient = dbo.Clients.IDClient " +
                    $"GROUP BY (dbo.Clients.Surname + ' ' + dbo.Clients.Name + ' ' + dbo.Clients.SecondName) ORDER BY Count(*) DESC;";
            }
            else if (Combo.SelectedIndex == 1)
            {
                strQ = $"SELECT (dbo.Dealer.Surname + ' ' + dbo.Dealer.Name + ' ' + dbo.Dealer.SecondName) as ПІБ, Count(*) as [Кількість Договорів] " +
                    $"FROM dbo.Contract INNER JOIN dbo.Dealer ON dbo.Contract.IDDealer = dbo.Dealer.IDDealer " +
                    $"GROUP BY (dbo.Dealer.Surname + ' ' + dbo.Dealer.Name + ' ' + dbo.Dealer.SecondName) ORDER BY Count(*) DESC;";
            }
            else 
            {
                strQ = $"SELECT (dbo.Dealer.Surname + ' ' + dbo.Dealer.Name + ' ' + dbo.Dealer.SecondName) as [ПІБ дилера], dbo.Contract.IDContract as [Номер договору], dbo.Car.Model as Модель, dbo.Contract.Date as Дата, (dbo.Clients.Surname + ' ' + dbo.Clients.Name + ' ' + dbo.Clients.SecondName)as [ПІБ клієнта] " +
                    $"FROM dbo.Contract INNER JOIN dbo.Dealer ON dbo.Contract.IDDealer = dbo.Dealer.IDDealer INNER JOIN dbo.Clients ON dbo.Contract.IDClient = dbo.Clients.IDClient INNER JOIN dbo.Car ON dbo.Contract.IDCar = dbo.Car.IDCar " +
                    $"ORDER BY (dbo.Dealer.Surname + ' ' + dbo.Dealer.Name + ' ' + dbo.Dealer.SecondName), dbo.Contract.IDContract;";
            }

            adapter = new SqlDataAdapter(strQ, connection);
            dt = new DataTable("Статистика");
            adapter.Fill(dt);
            if (Combo.SelectedIndex == 2)
                Output.AutoGeneratedColumns += setformat;
            Output.ItemsSource = dt.DefaultView;

            index = Combo.SelectedIndex;
            connection.Close();

            void setformat(object s, EventArgs k)
            {
                Output.AutoGeneratedColumns -= setformat;
                (Output.Columns[3] as DataGridTextColumn).Binding.StringFormat = "dd.MM.yyyy";
            }
        }
    }
}